### ISSUE TITLE
Create hierarchy to represent file types

### ISSUE THREAD

**Issue by miguel-branco** [raw-db/raw#38]
In `DataLocation.scala` we rely on mime-type string but that is somewhat fragile.

**Comment by nfsantos** [comment]
Revision: f49b5d01a312e12ac2ec64114d52e1997dad3cb6

**Comment by miguel-branco** [comment]
A few comments:
  * we can drop the `mimetype` altogether and just use the case classes; we only need a case class to the identify the file types, and then, per file type, add in a few type-specific properties in the constructor (e.g. the separator for CSV). This means the reference executor will also change to pattern match against those classes instead of against text strings (which is what we have but it's wrong because then we don't have compilation warning if we miss an implementation).
  * stylistic: use the standard ClassName for case classes; maybe move that hierarchy tree to a separate source file? also, follow the argument notation used elsewhere (e.g. `foo: String` instead of `foo:String`)

**Comment by nfsantos** [comment]
Fixed in revision: ee8cc494bca9adecb8fb2b2c68f1ff49d53b2633
