### ISSUE TITLE
crash: rule C6 (and probably others) doesn't pass the right variables to createPredicate

### ISSUE THREAD

**Issue by bgaidioz** [raw-db/raw#49]
In the smoke test if I put such query:

for (s <- students, p <- profs, d <- departments, s.office = p.office and p.name = d.prof) yield ...

(note there is one predicate but it's an "and" of two equalities, I suppose it's quite equivalent to s.office = p.office, p.name = d.prof) but in that second case we get a list of two predicates and it doesn't fail.

The Arg(idx) fails because idx = -1 when it's one predicate.

some info:

it comes from

CalculusTerm(CanonicalComp(m, Calculus.Gen(v, ExtractClassExtent(x)) :: r, p, e), Nil, w, AlgebraTerm(child))

where v is $7 and w is List($6) but p refers to three variables ($6, $7 and $8).

**Comment by miguel-branco** [comment]
Nested predicates were not being flattened. Now fixed in the new-executor branch.
