### ISSUE TITLE
CalculusPrettyPrinter should generate minimally parenthesized expresions

### ISSUE THREAD

**Issue by nfsantos** [raw-db/raw#50]
Currently, the pretty printer does not add parentheses to most arithmetic expressions. For instance, `a+(b*c)` and `(a+b)*c` are both represented as `a+b*c`. It should instead generate `a+b*c` and `(a+b)*c`, respectively, that is, with a minimal number of parenthesis.

**Comment by miguel-branco** [comment]
This issue was moved to raw-labs/raw#30
