### ISSUE TITLE
Error parsing expressions with several logical operators (eg., `a < b = c`)

### ISSUE THREAD

**Issue by nfsantos** [raw-db/raw#52]
The expression `(a < b) = c` is parsed correctly but the equivalent expression  `a < b = c` is not.
```
Parser error: [1.10] failure: `(' expected but end of source found

a < b = c
         ^
```

Parser also fails if the expression contains constants instead of variables, eg., the parser fails with `2 < 4 = false` but succeeds with `(2 < 4) = false`:

```
Parser error: [1.7] failure: string matching regex `\z' expected but `=' found

2 < 4 = false
      ^
```

**Comment by miguel-branco** [comment]
This issue was moved to raw-labs/raw#28
