### ISSUE TITLE
triple join (and I suppose more too) leads to a suboptimal algebra

### ISSUE THREAD

**Issue by bgaidioz** [raw-db/raw#54]
Something like 

for (s <- students, p <- profs, d <- departments, s.office = p.office, p.name = d.prof) yield ...

leads to the following tree where the reduce predicate should be in the below join.
```
reduce set $0.name $1.name = $2.prof <---
join true                                   <---------------
    join $0.office = $1.office
        select true
            scan (students)
        select true
            scan (profs)
    select true
        scan (departments)
```

**Comment by bgaidioz** [comment]
I tried to figure out a bit and didn't manage.

**Comment by bgaidioz** [comment]
I think rule C6 is computing p_w_v wrong.

current implementation is:
```
p.filter(pred => (w :+ v).toSet.map{idnNode: Calculus.IdnNode => idnNode.idn}.subsetOf(variables(pred).map{a => a.idn}))
```
which means we take predicates which contain at least _all_ variables of w+v (the filter means w+v is a subset of the variables of the predicate).
```

After debugging, brainstorming and checking the C++ implementation by the authors, I think it should be something like:

```
p.filter(pred => !p_v.contains(pred) && variables(pred).map{i: Calculus.IdnNode => i.idn}.subsetOf((w :+ v).toSet.map{i: Calculus.IdnNode => i.idn}))
```

that is: predicates which variables are a subset of w+v, but ignoring p_v (to avoid duplicates).

This is also what the authors implemented with this if..then..else:

```
list<Expr>* vars = free_variables(r->hd,Nil);       <- vars of the predicate
...
if (subset(vars,pattern_variables(right_pattern))) <- vars is a subset of Set(v) (it means vars = Set(v)
    rights = rights->cons(r->hd);  <- store it in p_v
else if (subset(vars,pattern_variables(left_pattern)
                                        ->append(pattern_variables(right_pattern)))) <- if subset of w+v
                     both = both->cons(r->hd); <- then in p_w
                  else rests = rests->cons(r->hd); <- else in p_rest
                };

```

**Comment by miguel-branco** [comment]
Good catch. I think we've seen >1 bug related to this one.
