### ISSUE TITLE
; needed on ExpBlock but newline ought to work

### ISSUE THREAD

**Issue by miguel-branco** [raw-db/raw#61]

**Comment by bgaidioz** [comment]
Just to log some comments. After testing quickly something a comprehension:

for (x <- values
      x = v
      x = true) yield x

due to some precedence of expressions over \n is parsed as if we had entered "x = v(x = true)". I'll check a bit more.

**Comment by miguel-branco** [comment]
This issue was moved to raw-labs/raw#23
