### ISSUE TITLE
Review use of fold vs foldLeft

### ISSUE THREAD

**Issue by nfsantos** [raw-db/raw#67]
The Scala executor is using `foldLeft()` to implement Reduce, which may be unnecessarily restrictive. Consider using `fold()`.

Notes:
* `foldLeft()` requires a binary operator and ensures left to right operation. `fold()` requires the operation to also be associative, which allows the implementation to choose internally the evaluation order.
* Spark does not support `foldLeft()` (hard to perform in a distributed fashion)

**Comment by miguel-branco** [comment]
This issue was moved to raw-labs/raw#21
