### ISSUE TITLE
Misleading error messages when projecting the wrong fields

### ISSUE THREAD

**Issue by miguel-branco** [raw-db/raw#68]
I was accidentally writing an invalid test case on the SemanticAnalyser with:
```
  assertRootType(
     """for (x <- things; a := x._1; b := x._2; c := x._3; d := x._4) yield set (_1 := a, _2 := d)""",
     SetType(RecordType(List(AttrType("_1", IntType()), AttrType("_2", SetType(FloatType()))))),
     world=TestWorlds.things
  )
```

... however, `things` does not contain fields `_1` or `_2`, ... but instead contains fields `a`, `b`, `set_a`, etc. 

The error message, however, is really confusing, complaining that e.g. `a` (the bound variable) has no type. The expected record type message, which does appear, is also confusing!

**Comment by bgaidioz** [comment]
Regarding the confusing error message about the record, what about this:

expected record having field 'x' but got record(patient_id=int)

Regarding "has no type", although we discussed that perhaps in this specific case we could hide the error, perhaps "type of a could not be inferred" would be more user-friendly.

**Comment by miguel-branco** [comment]
This issue was moved to raw-labs/raw#20
