### ISSUE TITLE
Improve anonymous case classes

### ISSUE THREAD

**Issue by miguel-branco** [raw-db/raw#82]
The code generation creates many anonymous case classes which could be implemented using Scala's Tuple2 instead.

In addition, we should replace the "anonymous" case class names from being hash codes to sequential integers, since it makes debugging easier.

**Comment by nfsantos** [comment]
The code generator creates case classes with names `UserRecordN` for each record which appears in the query results. The records used only internally are represented using tuples.

The goal is to improve readability of the generated code while minimizing the number of new classes generated.
