### ISSUE TITLE
wrong priority in parsing queries

### ISSUE THREAD

**Issue by torcato** [raw-db/raw#90]
In the following query  
''' for (t <- bools; t.A = t.B or true ) yield set t '''
the "or" will have higher priority than the "=" so it will be parsed as 
'''(t.A = t.B) or true '''
which will be simplified as 
''' for (t <- bools; true ) yield set t '''
if we write the parenthesis forcing the priority then the problem disappears

**Comment by miguel-branco** [comment]
I believe our priority is actually correct here.
Here's a comparison with Python:
```
>>> class T(object):
...     def __init__(self):
...             self.A = 1
...             self.B = 2
...
>>> t = T()
>>> t.A == t.B
False
>>> print (t.A == t.B or True)
True
```
so follows the same as ours.
