### ISSUE TITLE
Error parsing expressions with projections

### ISSUE THREAD

**Issue by torcato** [raw-db/raw#92]
the following expression
''' t.A and t.B '''
will be parsed as 
 RecordProj(
	MergeMonoid(
		AndMonoid(),
		RecordProj(
			IdnExp(IdnUse(t))
			,A
		)
		,IdnExp(IdnUse(t))
	)
	,B
)

instead of 

 MergeMonoid(
	AndMonoid(),
	RecordProj(
		IdnExp(IdnUse(t)),
		A
	),
	RecordProj(
		IdnExp(IdnUse(t)),
		B
	)
)

played a bit and 
division and multiplication have  the same problem,
but funny enough  "or" and  "addition" behave properly.

**Comment by miguel-branco** [comment]
This issue was moved to raw-labs/raw#13
