### ISSUE TITLE
Explore using the runtime macros to generate the query code.

### ISSUE THREAD

**Issue by nfsantos** [raw-db/raw#94]
We are currently using compile-time macros, including macro annotations and white-box macros. Neither of these features is guaranteed to be supported in the future. 

Additionally, compile-time macros is cumbersome as it requires an additional compilation step, which adds time and complexity.

Tasks:
- [ ] Explore if it is possible to generate the code using runtime macros. 
- [ ] Look into what is planned in the scala-meta project, the successor of scala.reflect.

**Comment by miguel-branco** [comment]
This issue was moved to raw-labs/raw#12
