### ISSUE TITLE
Selection does not return all elements

### ISSUE THREAD

**Issue by torcato** [raw-db/raw#96]
So I have a csv file, "graph3d.csv" which is used to draw a 3d graph.
x,y,z
0,0,50.000000
0,1,50.000000
....
39,38,62.544692
39,39,52.693841

so if I type the query 
graph3d
the returned list  misses the fields y or z for some values .
so for instance the first element actually only has z, the element after has y and z but no x,
some elements after then x appears (look at screenshot).

it looks like it happens when the value of x or y is zero, no idea why.

![screenshot from 2015-10-02 13 14 12](https://cloud.githubusercontent.com/assets/7079186/10245419/a1c69910-6907-11e5-965e-bbee5389f69f.png)

**Comment by miguel-branco** [comment]
This issue was moved to raw-labs/raw#11
