### ISSUE TITLE
loose old registered files if registering array in json

### ISSUE THREAD

**Issue by torcato** [raw-db/raw#97]
So just to try out I created a json which has only a 2d array, example  (might be illegal ):
[
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5]
]

it registered correctly but after that I could not query data that was registered before.
The only way to solve it was to delete the folder of this data and restart the scala rest server.

**Comment by miguel-branco** [comment]
This issue was moved to raw-labs/raw#10
